# Site settings
title: Modern Blog
description: Modern-Blog A Elegant template for Jekyll
keywords: покер, игра, Fun
author: Azarty
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://2earntodie.org/" # the base hostname & protocol for your site
