# Site settings
title: Секреты и методити как выиграть в онлайн казино 
description: Вы играете но постоянно в минусе? Заходи к нам и мы расскажем Вам как легко и просто выиграть в любой игре.
keywords: покер, игра, Fun
author: Fishka
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://2earntodie.org/" # the base hostname & protocol for your site

baseurl: /

paginate: 5

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"
  - "jekyll-minifier"

plugins: 
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives