# Site settings
title: Секреты и методити как выиграть в онлайн казино 
description: Вы играете но постоянно в минусе? Заходи к нам и мы расскажем Вам как легко и просто выиграть в любой игре.
keywords: покер, игра, Fun
author: Fishka
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://2earntodie.org/" # the base hostname & protocol for your site
